[versions]
algoutils = "0.7.2"

[libraries]
algoutils-student = { module = "org.tudalgo:algoutils-student", version.ref = "algoutils" }
algoutils-tutor = { module = "org.tudalgo:algoutils-tutor", version.ref = "algoutils" }
junit-pioneer = { module = "org.junit-pioneer:junit-pioneer", version = "2.1.0" }

[plugins]
algomate = "org.tudalgo.algomate:0.6.1"
jagr-gradle = { id = "org.sourcegrade.jagr-gradle", version = "0.10.2" }
